name: Publish NPM Package

on:
  push:
    branches:
      - dev # Adjust to your main branch name or specify the desired branch
    paths:
      - 'README.md' #this trigger is for testing purposes only

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
      with:
        path: dev/libs/react-ui/src/lib/header # Specify the path to checkout

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14 # Choose your Node.js version

    - name: Change Working Directory
      run: cd dev/libs/react-ui/src/lib/header

    - name: Install Dependencies
      run: npm install

    - name: Publish to GitHub Packages
      run: |
        echo "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}" > ~/.npmrc
        npm publish --registry=https://npm.pkg.github.com
      env:
        NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

